# For Pull Requests, we build only the first three jobs: autotools on Linux,
# cmake on Linux, and cmake on Windows 32 bit.
#
# For branch builds and cron builds (once a day), we build all the jobs. This is
# achieved using the "if: type IN (push, api, cron)" fields in the jobs list.

on: [pull_request, push] # FIXME: remove push

jobs:
  cmake-linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: sudo apt update && sudo apt install libconfig-dev libopus-dev libsodium-dev libgtest-dev libvpx-dev ninja-build pylint3 llvm
    - run: echo "~/.local/bin" >> $GITHUB_PATH
    - run: ./.travis/${{ github.job }} install
    - run: ./.travis/${{ github.job }} script
      env:
        CC: gcc
    - run: ./.travis/upload-coverage

  autotools-linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo update-ca-certificates
    - run: sudo apt update && sudo apt install libconfig-dev libopus-dev libvpx-dev
    - run: ./.travis/${{ github.job }} install
    - run: ./.travis/${{ github.job }} script
      env:
        CC: clang

  tox-bootstrapd-docker:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - run: ./.travis/${{ github.job }}

  # These are all passing, so I don't want to see them right now.
  # # FIXME(robinlinden): if: type IN (push, api, cron)
  # cmake-win32:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: ./.travis/${{ github.job }} install
  #   - run: ./.travis/${{ github.job }} script
  #     env:
  #       CC: gcc

  # # FIXME(robinlinden): if: type IN (push, api, cron)
  # cmake-win64:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: ./.travis/${{ github.job }} install
  #   - run: ./.travis/${{ github.job }} script
  #     env:
  #       CC: gcc

  # # FIXME(robinlinden): if: type IN (push, api, cron)
  # cmake-osx:
  #   runs-on: macos-10.15
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: ./.travis/${{ github.job }} install
  #   - run: ./.travis/${{ github.job }} script
  #     env:
  #       CC: clang

# TODO
# jobs:
#   include:
#     - stage: "Stage 1"
#       if: type IN (push, api, cron)
#       env: JOB=cmake-freebsd
#       install:       .travis/$JOB-stage1 install
#       script:        .travis/$JOB-stage1 script
#     - stage: "Stage 2"
#       if: type IN (push, api, cron)
#       env: JOB=cmake-freebsd
#       install:       .travis/$JOB-stage2 install
#       script:        .travis/$JOB-stage2 script
